v20220428

diff --git a/buildroot-external/board/arkmicro/ark1668e_devb_emmc/rootfs_overlay/etc/init.d/S03appinit b/buildroot-external/board/arkmicro/ark1668e_devb_emmc/rootfs_overlay/etc/init.d/S03appinit
--- a/buildroot-external/board/arkmicro/ark1668e_devb_emmc/rootfs_overlay/etc/init.d/S03appinit
+++ b/buildroot-external/board/arkmicro/ark1668e_devb_emmc/rootfs_overlay/etc/init.d/S03appinit
@@ -1,22 +1,55 @@
 #!/bin/sh
 
-ubiattach /dev/ubi_ctrl -m 6
-if  [ ! -d /data ];  then
-mkdir -p /data
-fi
-mount -o sync -t ubifs ubi1_0 /data
+start() {
+	if  [ ! -d /data ];  then
+	mkdir -p /data
+	fi
 
-mkdir -p /tmp/dev
-#ln -s /dev/memalloc /tmp/dev/memalloc
-#/etc/hx170dec_load.sh
-#/etc/hx280enc_load.sh
-ifconfig lo up
-ulimit -c unlimited
-#hostname CarPlay
-mdnsd&
-if  [ ! -f /data/carplay.ini ];  then
-cp -rf /etc/carplay.ini /data
-fi
-if  [ ! -f /data/auto.ini ];  then
-cp -rf /etc/auto.ini /data
-fi
+	mount /dev/mmcblk0p7 /data
+	if [ $? -eq 0 ]
+	then
+		echo "mount successfully!"
+	else
+		sync
+		sleep 1
+		mount /dev/mmcblk0p7 /data
+		if [ $? -ne 0 ]
+		then
+			echo "mount failed! then reformat the volume!"
+			mke2fs /dev/mmcblk0p7
+			sleep 1
+			mount /dev/mmcblk0p7 /data
+			sync
+		fi
+	fi
+
+	ifconfig lo up
+	mdnsd&
+	if  [ ! -f /data/carplay.ini ];  then
+	cp -rf /etc/carplay.ini /data
+	fi
+	if  [ ! -f /data/auto.ini ];  then
+	cp -rf /etc/auto.ini /data
+	fi
+}
+
+stop() {
+	echo "stop"
+}
+
+restart() {
+	stop
+	sleep 1
+	start
+}
+
+case "$1" in
+	start|stop|restart)
+		"$1";;
+	reload)
+		# Restart, since there is no true "reload" feature.
+		restart;;
+	*)
+		echo "Usage: $0 {start|stop|restart|reload}"
+		exit 1
+esac
